users, CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `password` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '0',
  `last_login_date` datetime DEFAULT NULL,
  `created_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `modified_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reset_password_token` varchar(255) DEFAULT NULL,
  `reset_password_expires` datetime DEFAULT NULL,
  `email_verified` tinyint(1) DEFAULT '0',
  `verification_token` varchar(255) DEFAULT NULL,
  `account_locked` tinyint(1) DEFAULT '0',
  `failed_login_attempts` int DEFAULT '0',
  `usertype` int DEFAULT '0',
  `pincode` char(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unq_email_usertype` (`email`,`usertype`),
  KEY `idx_email` (`email`,`usertype`),
  KEY `idx_phone` (`phone`,`usertype`)
);